apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: tidu-cluster
  region: ap-southeast-1
  version: 1.21
  tags:
    karpenter.sh/discovery: tidu-cluster

availabilityZones:
  - ap-southeast-1a
  - ap-southeast-1b

managedNodeGroups:
  - name: ng-medium
    availabilityZones:
      - ap-southeast-1a
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 10
iam:
  withOIDC: true
