apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - targetgroupbinding.yaml

helmCharts:
  - name: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    namespace: kube-system
    valuesFile: albc.yaml
    releaseName: r1
    includeCRDs: true
