apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.small"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["ap-southeast-1a"]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      karpenter.sh/discovery: tidu-cluster
    securityGroupSelector:
      kubernetes.io/cluster/tidu-cluster: owned
  ttlSecondsAfterEmpty: 30
