apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karpenter
resources:
  - ns.yaml

helmCharts:
  - name: karpenter
    repo: https://charts.karpenter.sh/
    namespace: karpenter
    releaseName: r1
    valuesFile: karpenter.yaml
    version: v0.7.3
    
