apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
spec:
  ingressClassName: kong
  rules:
  - host: httpbin.elb.aws.tidu.cc
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: httpbin-2.elb.aws.tidu.cc
    http:
      paths:
      - backend:
          service:
            name: httpbin-2
            port:
              number: 80
        path: /
        pathType: Prefix
