apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong
resources:
  - ns.yaml
  - ingressclass.yaml

helmCharts:
  - name: kong
    repo: https://charts.konghq.com
    namespace: kong
    releaseName: r1
    valuesFile: kong.yaml
    includeCRDs: true
